repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-json
        files: ^api/
    -   id: trailing-whitespace
        files: ^api/
    -   id: end-of-file-fixer
        files: ^api/
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: detect-private-key
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        files: ^api/
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--resolve-all-configs, --config-root, api]
        files: ^api/
-   repo: https://github.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
    -   id: flake8
        args: [--config, api/setup.cfg]
        files: ^api/
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
        - id: prettier
          files: ^web/src/