# Generated by Django 5.0.3 on 2024-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedurl",
            name="url",
            field=models.URLField(db_index=True, unique=True),
        ),
    ]
